// ========================================
// POEM DATA
// ========================================
const poems = [
    {
        id: "numeri-naturali",
        title: "Numeri naturali",
        date: "2024-02-29",
        lines: [
            "Gli alberi fogliano",
            "gli uccelli cantano",
            "mezza età della terra",
            "adolescenza della natura,",
            "incontenibile dai numeri",
            "che pure la definiscono.",
        ],
        note: "Scritta il 29 Febbraio, pensando a quanto la matematica è il miglior strumento che abbiamo per descrivere la natura, nonostante la natura non sarà mai imbrigliabile dai numeri. I primi quattro versi si riferiscono proprio alla primavera che stà arrivando, e descrivono come la natura sia complessa, come in un uomo possono esserlo l'adolescenza e la mezz'età, entrambi aggettivi che descrivono per bene anche la primavera.",
    },
    {
        id: "ciclo-dell-acqua",
        title: "Il ciclo dell'acqua",
        date: "2025-07-11",
        lines: [
            "Lenta muta la nube",
            "nell'ondoso specchio",
            "ciò che sarà oggi è",
            "per se stessa passando",
            "identici raggi di sole.",
            "",
            "E il due uno diventa",
            "separa e unisce",
            "finisce dove non sa",
            "ai suoi simili cantando",
            "una vecchia musica nuova",
        ],
        note: "Scritta in riva al mare, racconta dell'acqua e del suo percorso, focalizzandosi su una goccia. La nube, che è acuqa, si riflette nel mare, e pensa che essa è ciò che un domani sarà, chiudendo il ciclo dell'acqua. Ma nonostante essa continua il suo ciclo, il resto del mondo non cambia, i raggi del sole sono identici, e si separano e uniscono in un arcobaleno, mentre la nuvola precipita come pioggia nel mare, diventando uno. È sempre l'arcobaleno che finisce dove non sa, e canta la musica, cioè il rumore della pioggià che è vecchia come il mondo, eppure nuova ogni volta.",
    },
    {
        id: "foresta",
        title: "Foresta",
        date: "2025-08-26",
        lines: [
            "La verde mente folta",
            "senza trovare pace",
            "comunicando tace",
            "melodie cantando",
            "",
            "All'uccellin in cima",
            "fa eco la sua voce",
            "passando per la foce",
            "senza quiete andando",
            "",
            "Giunge al formicaio",
            "la mente si riposa",
            "vedendo la sua casa",
            "tranquillità gustando",
        ],
        note: 'Scritta pensando al paragone tra una foresta e il cervello: gli alberi corrispondono ai neuroni, le connessioni alle foglie e alle radici. Nella prima strofa si introduce il tema della foresta e della comunicazione, cioè delle melodie della foresta, come il vento tra gli alberi, che vengono cantate "senza trovar pace", senza tranquillità. La stessa cosa succede all\'uccellino della seconda strofa, che canta e sente solo la sua voce, evocando quindi un senso di solitudine, mentre dalla cima di un albero, scende verso la foce di un fiume, senza quiete (proprio perché canta). La terza strofa invece ritrova la pace e la tranquillità di una formica che ritorna al suo formicaio e che già pregusta la calma e il riposo che la dentro può trovare. Non a caso la formica, dato che le formiche non emettono suoni, e possono quindi rimanere tranquille.',
    },
    {
        id: "il-viaggio-della-medusa",
        title: "Il viaggio della medusa",
        date: "2025-08-28",
        lines: [
            "Ed ecco la medusa",
            "che domani si sposa",
            "ma la porta è chiusa",
            "e muore la mimosa.",
            "",
            "In cerca di una scusa",
            "in giornata afosa",
            "riparte la medusa",
            "triste e pensierosa.",
            "",
            "Tutto ciò che ha usa",
            "per cercare qualcosa",
            "che gli faccia da musa",
            "nella vita noiosa",
        ],
        note: "Scritta pensando ad un amore che non è corrisposto. La medusa si vuole sposare un domani, ma trova la porta chiusa, cioè il suo amore non è corrisposto, e muore la mimosa che ha portato dentro grazie alla felicità dell'amore. Subita la delusione va in giro cercando di capire il perché (una scusa) non sia stata accettata, in una giornata afosa, cioè calda e soffocante. Superato l'amore, rimane solo un vuoto, che deve essere colmato da qualcosa o qualcuno, e la medusa lo cerca senza sosta usando tutte le proprie risorse.",
    },
    {
        id: "transizione-di-fase",
        title: "Transizione di Fase",
        date: "2025-08-31",
        lines: [
            '"Attenti! Sta crollando"',
            "urla il capitano",
            "la cenere volando",
            "è rotta la verità.",
            "",
            "Caduta è la Torre",
            "in oceano di fiamme.",
            "Ecco prega e corre",
            "disperato si tuffò.",
            "",
            "In cerca di riparo",
            "arriva a nuova riva",
            "ora è tutto chiaro",
            "Ecco l'acqua sorgiva",
        ],
        note: "La transizione di fase è quel processo per cui una sostanza passa da uno stato della materia ad un altro. In questo contesto indica il cambio di idee, la rottura delle certezze vecchie per formare verità nuove. La poesia è un continuo parallelismo tra un castello che cade durante una battaglia e un soldato che, perso il castello e trovandosi senza certezze, infine giunge a una nuova idea, ad una nuova tranquillità data da una nuova sorgente.",
    },
    {
        id: "il-giardino-dietro-casa",
        title: "Il giardino dietro casa",
        date: "2025-08-31",
        lines: [
            "In giro per il mondo",
            "tanti piccoli posti",
            "io vado visitando:",
            "calmi luoghi nascosti.",
            "",
            "Sulla strada un segno",
            "di un vicino ignoto",
            "di curiosità lo degno",
            "ecco: scatto una foto.",
            "",
            "E dopo una vita",
            "con chi mi sta intorno",
            "vado per la salita:",
            "vecchi legami formo.",
        ],
        note: "Scritta ripensando a tutte le cose che ci stanno vicino, ma che non degnamo mai di uno sguardo. Questo finché non decidiamo di farci una passeggiata, e scoprire tante piccole cose che attirano la nostra curiosità, stupendoci molto più di quanto possa fare tutto il resto.",
    },
    {
        id: "discorso-temporale",
        title: "Discorso temporale",
        date: "2025-09-07",
        lines: [
            "Come parla il tempo",
            "nessuno lo comprende",
            "va avanti senza scampo:",
            "eppure lo si vende.",
            "",
            "Neutre notizie porta",
            "il ticchettio lento",
            "che pure ci conforta",
            "come un calmo vento.",
            "",
            "Nostalgia io sento",
            "di lontano ricordo",
            "e sentendo mi pento:",
            "sento dolore sordo.",
        ],
        note: "Questa poesia ha un significato più esplicito delle altre. Il tema principale è il tempo che passa e tutte le cose che porta (le parole che parla), come noi lo sprechiamo, la nostalgia e i rimpianti del passato.",
    },
    {
        id: "spese-di-contesto",
        title: "Spese di contesto",
        date: "2025-09-09",
        lines: [
            "Chi pagherà il costo",
            "della vita coerente",
            "del mio piccolo posto",
            "trovato finalmente.",
            "",
            "Oscuro è il motivo",
            "strana è la ragione",
            "fa principio attivo",
            "il contesto d'azione.",
            "",
            "Il perché io agisco",
            "sento nel fragore",
            "del girevole disco",
            "sul perpetuo rotore",
        ],
        note: "A volte vogliamo aderire a determinati principi, diciamo di voler e voler fare cose per aderire a quei principi, ma ci pesa, all'atto pratico, fare quelle cose: è questo il costo della coerenza. Allo stesso modo, il contesto ci influenza a credere e fare molte cose, ed anche questo è un costo che passiamo. I motivi però si trovano solo dentro di noi, scritti su quel disco, che è il cervello, che non si ferma mai.",
    },
    {
        id: "continuo",
        title: "Continuo",
        date: "2025-09-09",
        lines: [
            "In superficie arriva",
            "un pensiero profondo",
            "e vede sulla riva",
            "uno strano nuovo mondo.",
            "",
            "Quanti pari mai visti",
            "incontra sul cammino",
            "vecchi, giovani, misti",
            "ed esterni perfino.",
            "",
            "Ma come lui nessuno",
            "che possa fare da re",
            "si chinano uno ad uno",
            "finché pace non c'è.",
            "",
            "Un'inaspettata voce",
            "alzandosi veloce",
            "il nuovo re uccide",
            "tutti quanti deride.",
            "",
            "Finché piccolo nasce",
            "un pensiero in fasce",
            "dal mezzo egli proviene",
            "un'idea nuova sostiene.",
            "",
            "La pace egli riporta",
            "lottando con ardore",
            "il popolo conforta",
            "che segue con furore.",
            "",
            "Un ultimo sguardo lancia",
            "all'ordine che ha posto",
            "saziando la sua pancia",
            "e pagando ogni costo.",
            "",
            '"Addio" infine dice',
            "e torna al profondo",
            "dove guarda felice",
            "il continuo del mondo.",
        ],
        note: "Lo scontro tra idee diverse è un processo grandioso e terribile, sopratutto quando riguarda quei principi profondi, radicati in noi, sui quali basiamo buona parte della conoscenza. Questo processo può attraversare varie fasi, da quella distruttiva dello scontro a quelle costruttive di messa in ordine e lotta per nuove idee. Infine il processo si conclude con nuovi pensieri che divengono la base della conoscenza, in attesa anche questi di subire lo stesso processo dei loro predecessori.",
    },
    {
        id: "ricerca-di-luci",
        title: "Ricerca di luci",
        date: "2025-09-16",
        lines: [
            "Brama, ma non vuole",
            "cerca, ma non trova",
            "la fonte d'ogni sole",
            "dove nube non cova.",
            "",
            "Nella vita più volte",
            "si cade in una fossa",
            "a causa delle molte",
            "idee in carne ed ossa.",
            "",
            "Molte luci io vedo",
            "e vado in confusione",
            "per l'esponente io cedo",
            "che supera il milione.",
        ],
        note: "Quante volte ci sentiamo sopraffatti dalle idee? Ecco di cosa parla questa poesia.",
    },
    {
        id: "alberi-sul-lago",
        title: "Alberi sul lago",
        date: "2025-09-17",
        lines: [
            "Ecco un Lago montano",
            "innumerevoli alberi lo coprono",
            "con ombrosa luce di pace.",
            "Volano sull'acqua sostenuti",
            "da se stessi solo dipendono",
            "per avere nutrimento di vita",
            "e dare al mondo se stessi.",
        ],
        note: "Suggestioni di un paesaggio onirico.",
    },
    {
        id: "percezioni",
        title: "Percezioni",
        date: "2025-09-20",
        lines: [
            "Piccolo vecchie percezioni",
            "per lungo tempo dimenticate",
            "io nuovamente sento",
            "camminando per la vita.",
            "",
            "E da queste vecchie cose",
            "sempre nuove ne nascono",
            "in inaspettati strani modi",
            "che per un piccolo istante",
            "mi conquistano.",
            "",
            "E dall'unione nasco io",
            "un pezzo per volta:",
            "uno nel passato inconscio,",
            "uno nel presente scivoloso,",
            "uno nel futuro inafferrabile.",
        ],
        note: "Spesso sento delle sensazioni che fanno parte del mio passato. E con il passare del tempo queste si modificano, cambiano faccia e diventano qualcosa che non avrei mai pensato potessero essere.",
    },
    {
        id: "eco-nel-tempo",
        title: "Eco nel tempo",
        date: "2025-09-20",
        lines: [
            "La stasi temporale è quel momento",
            "in cui un qualcosa io sento.",
            "La stasi...",
            "Io sento...",
            "",
            "Un cristallo temporale è qualcosa",
            "in cui pace io cerco.",
            "Un cristallo...",
            "Io cerco...",
            "",
            "La pace temporale è quel processo",
            "in cui sensazioni io provo.",
            "La pace...",
            "Io provo...",
            "",
            "La sensazione temporale è qualcosa",
            "che con tutto me stesso io voglio.",
            "La sensazione...",
            "Io voglio...",
            "",
            "Il me stesso temporale io sono.",
            "Me stesso...",
            "Io sono.",
        ],
        note: "Ci sentiamo spesso intrappolati in un ciclo che non ha fine. Ma ci sono dei momenti che non vorremmo che passino mai.",
    },
    {
        id: "cura-alla-solitudine",
        title: "Cura alla solitudine",
        date: "2025-09-23",
        lines: [
            "Quando sei solo nella stanza",
            "esci fuori e vai a guardare",
            "lo specchio vivente che danza",
            "che per le vie del mondo appare.",
            "",
            "Eppure per noi è molto difficile",
            "parlare con il riflesso esterno",
            "poiché diverso è quanto è simile:",
            "egli è unico rifugio nell'inverno.",
            "",
            "Solo negandoci troviamo il tesoro",
            "che nel mondo ha più valore",
            "eppure lo scambiamo per arido oro",
            "e poi ci lamentiamo per lunghe ore.",
        ],
        note: "Quanto è difficile confrontarsi con la realtà delle altre persone, con i loro sentimenti, con l'amore, con l'amicizia.",
    },
    {
        id: "espressione-esponenziale",
        title: "Espressione esponenziale",
        date: "2025-10-01",
        lines: [
            "Quello che un verso può diventare",
            "l'occhio attento ce lo deve dire",
            "facendo così l'euristica dominare.",
            "",
            "Combinazioni infinite ci sono",
            "che contarle ti fa invecchiare",
            "come musica con più di un tono",
            "",
            "In questo quello che facciamo è vita",
            "che a tentoni cerca di migliorare",
            "per cupe valli facendo una gita.",
        ],
        note: "La realtà che vediamo è un'esplosione esponenziale di molte variabili, che solo l'occhio umano, come la selezione naturale, possono cercare di dominare tramite l'euristica. è da qui che nasce l'arte.",
    },
    {
        id: "in-giro-ispirazioni",
        title: "In giro, ispirazioni",
        date: "2025-10-01",
        lines: [
            "Come il suono ci ispira",
            "vita ed esperienze possiamo fare",
            "tutte le volte a riprovare",
            "come a se il tempo ci tira.",
            "",
            "Colori liberi alla confusione vanno",
            "tanto che molti vogliono cancellare",
            "perché non vedono ciò che appare",
            "e la libertà della vita non sanno.",
            "",
            "Colori e suoni insieme stanno",
            "per il nostro diletto lavorare",
            "che ci porta sempre a pensare:",
            "tante nuove esperienze diverranno.",
        ],
        note: "Quando siamo in giro, come quando siamo soli, alcuni suoni ed alcuni colori ci ispirano grandi emozioni. I colori possono sembrare anche confusi, ma non per alcuni a cui questi colori donano vita e, insieme ai suoni, generano nuove esperienze.",
    },
    {
        id: "per-i-picchi",
        title: "Per i picchi",
        date: "2025-10-01",
        lines: [
            "Ciò che ci fa stare bene",
            "è l'idea di qualcosa di banale",
            "che ci faccia spostare di un canale",
            "la ricerca della nostra vita.",
            "",
            "Mi giro, mi volto",
            "di nuovo all'inizio mi trovo",
            "proprio all'uscita del mio covo",
            "che per molto vicino mi stà.",
            "",
            "Mi sposto, scappo un po'",
            "ma dalle ombre fuga non c'è",
            "tanto che la testa mi gira come te",
            "insieme scalando questa via.",
            "",
            "Picchi improvvisi io vedo:",
            "gioia al pensiero di salire",
            "ma si abbassa prima di partire",
            "e di nuovo sono in questo piatto mar.",
        ],
        note: "Una nuova idea ci spesso ci conquista, fino a quando non ci rendiamo conto che di fatto è una cosa normalissima, ci passa l'entusiasmo e torniamo come prima.",
    },
    {
        id: "radici-di-me",
        title: "Radici di me",
        date: "2025-10-04",
        lines: [
            "Dentro di me radici profonde",
            "l'originario albero ha messo",
            "tanto che anche adesso",
            "il ferro non rompe le onde",
            "della vita piantata a terra.",
            "",
            "E mentre sempre più",
            "da essa lontano vado",
            "triste sono non di rado",
            "per il verde che non vè più:",
            "solo esso vita può dare.",
        ],
        note: "Sempre più stiamo andando verso un mondo fatto di metallo e silicio. Ogni tanto è bene tornare alla natura, alle foglie, alle radici.",
    },
    {
        id: "dove-mi-trovo",
        title: "Dove mi trovo",
        date: "2025-10-06",
        lines: [
            "Scherzare piace al passaggio",
            "delle comete, e del saggio,",
            "del niente, del poco, del tutto",
            "pieno di nascita e di lutto.",
            "",
            "A volte, corto",
            "finché non morto",
            "è il gaio sentire",
            "del gioco a non finire.",
            "",
            "A quel punto decisamente lungo diventa",
            "e più va avanti e più la noia ritenta:",
            "il controllo vuole e mai se ne vuole andare",
            "a casa della pace non mi vuole portare.",
            "",
            "Infine sveglio mi ritrovo",
            "senza buco nero, senza vuoto covo",
            "e nulla mi rimane da fare",
            "se non il tempo imparare ad apprezzare.",
        ],
        note: "A volte il tempo ci sembra lungo, a volte ci sembra corto. Tutto dipende da noi, da come lo trascorriamo. A volte siamo nel vuoto, a volte vicino ad un buco nero, ma poi quello che conta è imparare ad apprezzarlo.",
    },
    {
        id: "lento-e-cangiante",
        title: "Lento e cangiante",
        date: "2025-10-20",
        lines: [
            "Lento e cangiante",
            "ma noi nessun pixel",
            "vediamo mutante.",
            "",
            "Di volta in volta",
            "traslato è stato",
            "distanza non molta.",
            "",
            "Ma la somma",
            "grande diventa",
            "tanto che in overflow",
            "manda la gomma.",
        ],
        note: "I cambiamenti sono lenti e continui. Noi spesso non ce ne rendiamo conto. Ma ad un certo punto, vengono accumulati così tanti cambiamenti che è impossibile tornare indietro. Questa è anche una delle teorie più accreditate per quanto riguarda l'invecchiamento: si accumulano progressivamente tanti errori nel DNA.",
    },
    {
        id: "calma-delle-piante",
        title: "Calma delle piante",
        date: "2025-10-25",
        lines: [
            "La danza di lance",
            "delizia le pance",
            "dell'occhio e del cuore.",
            "",
            "Da solo per ore",
            "sto col mio avo",
            "una buca io scavo.",
            "",
            "Pianto un virgulto",
            "che ricorda un sussulto",
            "che insegna chi sono.",
            "",
            "Rosso è il dono",
            "della lunga vita",
            "in moto, infinita.",
        ],
        note: "Le piante, come i nostri avi, ci possono insegnare tantissimo, se solo vorremmo ascoltarli.",
    },
    {
        id: "semplice-o-complesso",
        title: "Semplice o Complesso",
        date: "2025-11-11",
        lines: [
            "In questa realtà",
            "mi sento schiacciato",
            "dalla complessità",
            "dell'universo infinito.",
            "Conoscendo l'errore:",
            "converge il semplice",
            "in realtà indeterminate",
        ],
        note: "Ci sono due realtà infinitamente semplici, che sono la realtà fisica vera e propria, dove non esiste astrazione e tutto e uguale solo a se stesso, e la realtà di Dio, che è infinitamente semplice perché racchiude tutto in se stesso: Amore. Ma noi viviamo nella terra di mezzo, in questa infinita complessità.",
    },
    {
        id: "problemi-di-spazio",
        title: "Problemi di spazio",
        date: "2025-11-20",
        lines: [
            "Col tempo la memoria",
            "io devo deallocare",
            "per fare un po' baldoria.",
            "",
            "Non voglio dimenticare",
            "i bei momenti di vita",
            "ma spazio io Devo fare.",
            "",
            "Nell'overflow partita",
            "ci perde ogni persona",
            "fin quando tutta è finita.",
        ],
        note: "Ogni tanto abbiamo bisogno di nuovo spazio nella nostra vita, per poter iniziare nuove cose, nuovi percorsi. Non possiamo semplicemente continuare ad accumulare, per il semplice fatto che noi siamo in grado di gestire solo un numero costante di cose contemporaneamente",
    },
    {
        id: "assioma",
        title: "Assioma",
        date: "2025-11-21",
        lines: [
            "Ho trovato un assioma",
            "in un angolo era posto",
            "a guardia di una persona.",
            "",
            "Egli è principio di ogni",
            "buona cosa che avviene",
            "all'inizio dei miei sogni.",
            "",
            "Ma svegliandomi io penso",
            "a che serve un assioma?",
            "Questo non ha senso.",
            "",
            "Camminando per la via",
            "di nuovo l'assioma vedo",
            "ma lo caccio via via.",
            "",
            "Un nuovo assioma ho trovato",
            "che più di tutto mi attrae",
            "ora ho notato il vecchio stonato.",
        ],
        note: "Tutti noi in fondo ci basiamo su qualche regola morale interiore che è alla base delle decisioni che prendiamo. In questo, le regole prese in esame in questa poesia sono due: dare per scontato che gli altri siano buoni ed amare gli altri a prescindere da ciò. Se la prima, ad un primo esame, può sembrare quella corretta, nella poesia mi rendo conto che in realtà la seconda è superiore.",
    },
    {
        id: "uscendo-di-casa",
        title: "Uscendo di casa",
        date: "2025-12-13",
        lines: [
            "Uscendo di casa per la fretta",
            "una porta sbatto forte",
            "danno: è rotto il vetro",
            "userò la porta sul retro.",
            "",
            "Al ritorno vedo schegge:",
            "mi illuminano di Infiniti",
            "riflessi soli e indefiniti",
            "di un concetto, di un gregge.",
            "",
            "Con pazienza riunisco",
            "infiniti pezzi di luce",
            "finchè il pensiero finisco",
            "per disegnare come posso.",
            "",
            "Fuori ne viene cangiante",
            "un armadio a due ante",
            "dove me stesso ripongo",
            "per un riflesso futuro di me.",
        ],
        note: "Per creare dei posti in cui riporre le nostre idee, dobbiamo prima uscire dalla nostra confort zone, e poi ricostruire tutte le idee in modo che trasmettano la vera essenza di ciò che vogliamo dire, guardandole da molti punti diversi. Questa poesia è una metafora per questa cosa.",
    },
    {
        id: "entropia-naturale",
        title: "Entropia naturale",
        date: "2026-02-20",
        lines: [
            "Vento soffia nell'erba del mio cuore",
            "cresce, s'ingrossa, diventa calore.",
            "Disordine sparso che ordine lede",
            "si gira si perde eppure egli vede",
            "entropico lago.",
        ],
        note: "La natura è capace di crare e distruggere l'ordine delle cose, sia fuori che dentro di noi.",
    },
    {
        id: "buco-nero-buco-bianco",
        title: "Buco nero, Buco bianco",
        date: "2026-04-23",
        lines: [
            'Apro gli occhi al mattino',
            'e mi sveglio buco nero',
            'Vorrei, vorrei, ma non riesco a smettere.',
            'Li richiudo alla sera',
            'e sono più sazio che mai',
            'di stelle ripieno',
            'di salute un po\' meno.',
            '',
            'Un giorno apro gli occhi',
            'ma nessuno intorno a me.',
            'Resto affamato, piango perché',
            'nuova voci oggi non ci sono,',
            'nella via lattea che attraversa la città.',
            '',
            'Poi mi ritrovo buco bianco',
            'eccomi sono qui che aspetto',
            'la lenta armonia delle cose',
            'che ho costruito dentro.'
        ],
        note: "Sempre più spesso siamo in preda ad una bulimia di contenuti, di informazioni. Ma questo non ci può fare bene.",
    },
    {
        id: "vita-di-bit",
        title: "Vita di Bit",
        date: "2026-04-23",
        lines: [
            'Alba di nuovo mondo ora inizia',
            'quando fosche acque si calmano',
            'si mostra il fiore senza malizia',
            'le stelle il grande capo saltano.',
            '',
            'Si sveglia il formicaio rumoroso',
            'mille suoni sentendo ricominciare',
            'ecco che inizia il primo viavai brioso',
            'necessario al nostro sostentare.',
            '',
            'Per strada nessuno, poi uno, poi mille',
            'ingarbugli si creano e rompono',
            'destinazione bramano pupille',
            'finchè alti valori non leggono.',
            '',
            'Da qualche parte in questo contesto',
            'mentre ruotano veloci elettroni',
            'finché nasce un piccolo Bit di testo',
            'tra corde di fulmini e tuoni.',
            '',
            'Una grande magia avviene nell\'istante',
            'che l\'universo viene dimezzato',
            'nessuno sa quanto Bit è importante',
            'fin quando quanto quantizzato è stato.',
            '',
            'Un eterno risultato ha portato',
            'una sola decisione, una misura',
            'che non può essere più cambiato',
            'se non forse solo dall\'usura.',
            '',
            'Viaggia veloce per lunghi giorni,',
            'in segnali ripone la sua esistenza,',
            'in attesa che vecchio ordine torni',
            'distrutto da lui con la sua presenza.',
            '',
            'Genera scintille mentre per strada va',
            'guardando reami finché magia non ha',
            'amici lui cerca perché solo non sta',
            'bei libri leggendo finch\'egli non sa',
            '',
            'Tanti mondi viaggia ai più sconosciuti',
            'mentre va per via vede cifre nuove',
            'che volano su adorabili pennuti',
            'e vegliano dall\'alto chi si muove.',
            '',
            'Finalmente un giorno a lungo atteso',
            'Per il piccolo Bit infine arriva',
            'di lasciare questo suo grande peso',
            'di tirare la barca sulla riva',
            '',
            'Una bella cifra gemella lui trova',
            'ed ecco è formata una catena.',
            'Nel suo cuore entropia non cova',
            'il Creatore ringrazia ad ogni cena.',
            '',
            'Nella sequenza principale lui entra',
            'finalmente normalità lui sente',
            'nella danza Bit si concentra',
            'finché le stagioni passano lente.',
            '',
            'Qui Bit il suo recinto costruisce',
            'che insieme agli amici di una vita',
            'la terra cura, con le piante guarisce',
            'mentre poesie di mondo lontano cita.',
            '',
            'Un giorno, un mese, un anno passa',
            'cresce la vita, che il tempo aumenta.',
            'Poco si lamenta di qualche tassa',
            'che paga sul guadagno della menta.',
            '',
            'Sembra che questo mondo non finisce',
            'mai pensando ad un futuro diverso.',
            'è difficile trovare qualcosa che unisce',
            'che sposti da lì quel Bit di verso.',
            '',
            'Un giorno infine arriva un qualcosa',
            'per tutti difficile da ignorare',
            'tant\'è vero che Bit sfidarlo non osa',
            'gira, ruota, sta li ad osservare.',
            '',
            'Come un cuoco che cibi miscela',
            'come in un gioco che cambia carte',
            'come un pittore che scambia la tela',
            'tutto finisce come opera d\'arte.',
            '',
            'Così Bit ecco ritrova se stesso',
            'per strade buie si perde girando',
            'ecco non sa più cosa fare adesso',
            'una soluzione egli cerca cantando.',
            '',
            'Tutto fa tutto gira tutto guarda',
            'si Volta trema e infine rivolta',
            'crepuscolo buio nell\'ora tarda',
            'la vera bianca serenità è tolta.',
            '',
            'L\'universo ora è più grande',
            'torna all\'inizio, alla generazione',
            'che guarda alta come le Ande',
            'nondeterministica creazione.',
            '',
            'Una vera bilancia di riflesso',
            'che è sempre in ondoso moto',
            'nel suo grande piano complesso',
            'tanto difficile farle una foto.',
            '',
            'L\'indomani tutto riparte dal cielo',
            'dalla supernova che scintilla',
            'da chi ammira un po\' su un telo',
            'e chi ignora: La vita arzilla.',
            '',
            'Nessuno conosce l\'avvenuto fatto',
            'nell\'eternità un soffio è passato',
            'nel mondo ha svolto un atto',
            'finché tutto è dimenticato.',
            '',
            'Piccola luce piano scompare',
            'rimane solo un buco nero',
            'che tutto nuovo è pronto a creare',
            'solo ciò che è vero.'
        ],
        note: "Grande storia di un Bit, che viene prima generato, fa la sua vita e poi scompare.",
    },
    {
        id: "scalata-alla-conoscenza",
        title: "Scalata alla conoscenza",
        date: "2026-05-26",
        lines: [
            'Scende una goccia di sudore',
            'su una foglia cade come rugiada',
            'ma dal mattino molto è passato.',
            '',
            'Guardo sotto, che errore!',
            'chiudo gli occhi, mi stringo in me.',
            'Tanta piacevole aria fresca',
            'Sento dentro che cammina.',
            '',
            'Poi esce,',
            'e mi giro verso l\'alto e vedo',
            'che l\'albero non ha smesso di crescere:',
            'in fondo, anche lui è giovane.',
            '',
            'Stendo la mano, il muscolo teso',
            'un nuovo ramo conquisto',
            'mai quassù sono stato.',
            '',
            'Colgo il mondo:',
            'incanto, a bocca aperta rimango.',
            'Ormai ho deciso,',
            'da quassù non scendo.'
        ],
        note: "La conoscenza è come un albero, che nella vita piano piano scaliamo.",
    },
    {
        id: "punto-focale",
        title: "Punto focale",
        date: "2026-07-11",
        lines: [
            'Qui nasce nel fuoco',
            'uno splendido gioco.',
            '',
            'Un po\' di vento ci vuole',
            'per movimentare',
            'l\'armonia di luce.',
            '',
            'Luce che il sole regala',
            'non solo a natale',
            'ma anche per il mare',
            'di una piccola baia.',
            '',
            'Baia che incontra,',
            'caldo freddo mischia',
            'per darmi nell\'anima',
            'una perfetta immagine di te.'
        ],
        note: "Cosa è l'amore se non un fuoco, un gioco, movimentato, in armonia, che la natura ci regala?",
    },
    {
        id: "momento-d-inerzia",
        title: "Momemto d'inerzia",
        date: "2026-08-09",
        lines: [
            'In uno c\'è tutto',
            'desiderio di frutto',
            'eterno, se trovato',
            'piccolo, se parlato.',
            '',
            'Cangiante colore',
            'muta il sapore',
            'del mondo racchiuso',
            'in un istante confuso.',
            '',
            'Eppure mi muove',
            'un momento etereo,',
            'nel cielo del cuore',
            'un veloce aereo.',
            '',
            'Momento ecco passa:',
            'mi spinge in avanti,',
            'mettendo su massa.',
            'Come palla di neve',
            'che rotola piano.'
        ],
        note: "La realtà divisa in piccoli istanti in cui l'attenzione del momento ci da piacere.",
    }
];
