#!/bin/bash

echo "Running custom pre-commit hook..."

#glyphhanger index.html --subset=Neuton/Neuton-Regular.ttf || { 
#    echo "Command failed. Aborting commit."; 
#    exit 1; 
#}

python3 hooks/minimize.py full.html index.html || { 
    echo "Python script failed. Aborting commit."; 
    exit 1; 
}

git add index.html

echo "Pre-commit checks passed successfully!"